# Generated by Django 2.0 on 2018-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='tumlbr',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tumblr',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_plus',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pinterest',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
