# Generated by Django 2.0 on 2018-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0002_auto_20180903_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
