# Generated by Django 2.0 on 2018-09-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0003_sitesettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_banner',
            field=models.ImageField(blank=True, null=True, upload_to='site'),
        ),
    ]
