# Generated by Django 2.0 on 2018-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0006_auto_20180907_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
