# Generated by Django 2.0 on 2018-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0008_sitesettings_post_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='domain',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='post_detail',
            field=models.SmallIntegerField(default=1000, help_text='Haber detayında sayfa başına düşen karakter sayısı örn:1000', verbose_name='Haber Detay Karakter'),
        ),
    ]
