# Generated by Django 2.0 on 2018-09-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('mail', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('web_site', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.News', verbose_name='Haber')),
            ],
        ),
    ]
