# Generated by Django 2.0 on 2018-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='subcategory'),
            preserve_default=False,
        ),
    ]
