# Generated by Django 2.0 on 2018-09-13 08:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('spot', models.CharField(max_length=255)),
                ('detail', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='News')),
                ('video_url', models.CharField(default='0', help_text='Eğer video eklemek istemiyorsanız burası 0 olarak kalmalı', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('viewed', models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('tags', models.CharField(help_text='Lütfen kelimelerin arasında virgül kullanınız ve boşluk kullanmayınız', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.Category')),
            ],
            options={
                'ordering': ('title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='NewsGallery')),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.News')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subcategory')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.Category')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='parent', on_delete=django.db.models.deletion.CASCADE, to='haberler.SubCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
