# Generated by Django 2.0 on 2018-09-06 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('spot', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='News')),
                ('video_url', models.CharField(default='0', help_text='Eğer video eklemek istemiyorsanız burası 0 olarak kalmalı', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('viewed', models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('tags', models.CharField(help_text='Lütfen kelimelerin arasında virgül kullanınız ve boşluk kullanmayınız', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='NewsGallery')),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.News')),
            ],
        ),
    ]
