# Generated by Django 2.0 on 2018-09-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='taglar',
        ),
    ]
