# Generated by Django 2.0 on 2018-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_auto_20180906_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='taglar',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='news',
            name='yeni',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
