# Generated by Django 2.0 on 2018-09-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_auto_20180906_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='yeni',
        ),
    ]
