# Generated by Django 2.0 on 2018-09-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory'),
        ('haberler', '0004_remove_news_yeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory'),
            preserve_default=False,
        ),
    ]
