# Generated by Django 2.0 on 2018-09-07 09:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_news_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='parent', on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory'),
        ),
    ]
