# Generated by Django 2.0 on 2018-09-08 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0006_auto_20180907_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
