# Generated by Django 2.0 on 2018-09-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_auto_20180908_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title', 'pk')},
        ),
    ]
